const usuarios = [
  {
    id: 1,
    user: "thuberman@uade.edu.ar",
    pass: "1203134",
    country: "Argentina",
    nombre: "Huberman, Tomas",
  },
  {
    id: 2,
    user: "yaadonmolina@uade.edu.ar",
    pass: "1038464",
    country: "Argentina",
    nombre: "Adon Molina, Yael Agustina",
  },
  {
    id: 3,
    user: "aastuni@uade.edu.ar",
    pass: "1176754",
    country: "Argentina",
    nombre: "Astuni, Atenas",
  },
  {
    id: 4,
    user: "sbaldrich@uade.edu.ar",
    pass: "1163135",
    country: "Argentina",
    nombre: "Baldrich, Serena",
  },
  {
    id: 5,
    user: "cobarrientos@uade.edu.ar",
    pass: "1150515",
    country: "Argentina",
    nombre: "Barrientos, Constanza",
  },
  {
    id: 6,
    user: "benbilbao@uade.edu.ar",
    pass: "1152407",
    country: "Argentina",
    nombre: "Bilbao, Benjamin",
  },
  {
    id: 7,
    user: "rbonanno@uade.edu.ar",
    pass: "1163401",
    country: "Argentina",
    nombre: "Bonanno, Roman",
  },
  {
    id: 8,
    user: "mbrotto@uade.edu.ar",
    pass: "1128090",
    country: "Argentina",
    nombre: "Brotto, Mateo Benjamin",
  },
  {
    id: 9,
    user: "tcaffarelli@uade.edu.ar",
    pass: "1154491",
    country: "Argentina",
    nombre: "Caffarelli, Tomas",
  },
  {
    id: 10,
    user: "ccastrilli@uade.edu.ar",
    pass: "1186256",
    country: "Argentina",
    nombre: "Castrilli, Camila Belen",
  },
  {
    id: 11,
    user: "ccanon@uade.edu.ar",
    pass: "1145694",
    country: "Argentina",
    nombre: "Cañon, Camila Delfina",
  },
  {
    id: 12,
    user: "ecoronel@uade.edu.ar",
    pass: "1185307",
    country: "Argentina",
    nombre: "Coronel, Elian German",
  },
  {
    id: 13,
    user: "vitorre@uade.edu.ar",
    pass: "1150983",
    country: "Argentina",
    nombre: "Della Torre, Virginia",
  },
  {
    id: 14,
    user: "ldispalatro@uade.edu.ar",
    pass: "1149156",
    country: "Argentina",
    nombre: "Di Spalatro, Luciana",
  },
  {
    id: 15,
    user: "mandiaz@uade.edu.ar",
    pass: "1170168",
    country: "Argentina",
    nombre: "Diaz, Manuela",
  },
  {
    id: 16,
    user: "dadiazdoria@uade.edu.ar",
    pass: "1120404",
    country: "Argentina",
    nombre: "Diaz Doria, Darly Andrea",
  },
  {
    id: 17,
    user: "debertz@uade.edu.ar",
    pass: "1158149",
    country: "Argentina",
    nombre: "Ebertz, Dafne",
  },
  {
    id: 18,
    user: "vfusaro@uade.edu.ar",
    pass: "1151458",
    country: "Argentina",
    nombre: "Fusaro, Valentina",
  },
  {
    id: 19,
    user: "lgentile@uade.edu.ar",
    pass: "1128484",
    country: "Argentina",
    nombre: "Gentile, Luciano",
  },
  {
    id: 20,
    user: "magraff@uade.edu.ar",
    pass: "1176639",
    country: "Argentina",
    nombre: "Graff, Martina",
  },
  {
    id: 21,
    user: "romhernandez@uade.edu.ar",
    pass: "1164045",
    country: "Argentina",
    nombre: "Hernandez Maczan, Romina",
  },
  {
    id: 22,
    user: "fliribarren@uade.edu.ar",
    pass: "1152103",
    country: "Argentina",
    nombre: "Iribarren, Florencia",
  },
  {
    id: 23,
    user: "sisla@uade.edu.ar",
    pass: "1132373",
    country: "Argentina",
    nombre: "Isla, Santiago",
  },
  {
    id: 24,
    user: "clarralde@uade.edu.ar",
    pass: "1144883",
    country: "Argentina",
    nombre: "Larralde, Clara Maria",
  },
  {
    id: 25,
    user: "mmarazzi@uade.edu.ar",
    pass: "1149943",
    country: "Argentina",
    nombre: "Marazzi, Morella Lucia",
  },
  {
    id: 26,
    user: "mmarchetto@uade.edu.ar",
    pass: "1157780",
    country: "Argentina",
    nombre: "Marchetto, Mia",
  },
  {
    id: 27,
    user: "gmarshall@uade.edu.ar",
    pass: "1112550",
    country: "Argentina",
    nombre: "Marshall, Guido Uriel",
  },
  {
    id: 28,
    user: "smartinez10@uade.edu.ar",
    pass: "1158513",
    country: "Argentina",
    nombre: "Martinez Fondeville, Sol",
  },
  {
    id: 29,
    user: "chmauro@uade.edu.ar",
    pass: "1149699",
    country: "Argentina",
    nombre: "Mauro, Chiara",
  },
  {
    id: 30,
    user: "mmenghi@uade.edu.ar",
    pass: "1163532",
    country: "Argentina",
    nombre: "Menghi, Maria Belen",
  },
  {
    id: 31,
    user: "mminniti@uade.edu.ar",
    pass: "1159466",
    country: "Argentina",
    nombre: "Minniti, Marianela",
  },
  {
    id: 32,
    user: "jmoltedo@uade.edu.ar",
    pass: "1144763",
    country: "Argentina",
    nombre: "Moltedo, Juan Manuel",
  },
  {
    id: 33,
    user: "gemorano@uade.edu.ar",
    pass: "1163127",
    country: "Argentina",
    nombre: "Morano, Gervasio",
  },
  {
    id: 34,
    user: "jamosquera@uade.edu.ar",
    pass: "1099139",
    country: "Argentina",
    nombre: "Mosquera Cardenas, Javier Alejandro",
  },
  {
    id: 35,
    user: "sodierna@uade.edu.ar",
    pass: "1116105",
    country: "Argentina",
    nombre: "Odierna, Sofia",
  },
  {
    id: 36,
    user: "votaola@uade.edu.ar",
    pass: "1137262",
    country: "Argentina",
    nombre: "Otaola, Valentina",
  },
  {
    id: 37,
    user: "mipagani@uade.edu.ar",
    pass: "1150191",
    country: "Argentina",
    nombre: "Pagani, Milena",
  },
  {
    id: 38,
    user: "tperrincanelli@uade.edu.ar",
    pass: "1156028",
    country: "Argentina",
    nombre: "Perrin Canelli, Tomás Agustín",
  },
  {
    id: 39,
    user: "mpicone@uade.edu.ar",
    pass: "1150418",
    country: "Argentina",
    nombre: "Picone, Maria Agustina",
  },
  {
    id: 40,
    user: "jrobbio@uade.edu.ar",
    pass: "1144820",
    country: "Argentina",
    nombre: "Robbio, Juana",
  },
  {
    id: 41,
    user: "sscarano@uade.edu.ar",
    pass: "1179272",
    country: "Argentina",
    nombre: "Scarano, Segundo",
  },
  {
    id: 42,
    user: "dsuzak@uade.edu.ar",
    pass: "1159311",
    country: "Argentina",
    nombre: "Suzak, Daniel Alejandro",
  },
  {
    id: 43,
    user: "ttaboada@uade.edu.ar",
    pass: "1139014",
    country: "Argentina",
    nombre: "Taboada, Tobias",
  },
  {
    id: 44,
    user: "rovarela@uade.edu.ar",
    pass: "1152458",
    country: "Argentina",
    nombre: "Varela, Rocío Magali",
  },
  {
    id: 45,
    user: "swilliams@uade.edu.ar",
    pass: "1126812",
    country: "Argentina",
    nombre: "Williams, Sofia",
  },
  {
    id: 46,
    user: "ryanezlinares@uade.edu.ar",
    pass: "1163807",
    country: "Argentina",
    nombre: "Yanez Linares, Rachel Elena",
  },
  {
    id: 47,
    user: "manu",
    pass: "1234",
    country: "Argentina",
    nombre: "Manuel Garcia",
  },
  {
    id: 48,
    user: "emma",
    pass: "1234",
    country: "UK",
    nombre: "Emma Watson",
  },
  {
    id: 49,
    user: "ricardo",
    pass: "1234",
    country: "Argentina",
    nombre: "Ricardo Darín",
  },
  {
    id: 50,
    user: "daniel",
    pass: "1234",
    country: "Germany",
    nombre: "Daniel Brühl",
  },
  {
    id: 51,
    user: "penelope",
    pass: "1234",
    country: "Spain",
    nombre: "Penélope Cruz",
  },
  {
    id: 52,
    user: "franco",
    pass: "1234",
    country: "Argentina",
    nombre: "Franco Colapinto",
  },
  {
    id: 53,
    user: "beyonce",
    pass: "1234",
    country: "USA",
    nombre: "Beyoncé Knowles",
  },
  {
    id: 54,
    user: "sergio",
    pass: "1234",
    country: "Argentina",
    nombre: "Sergio Agüero",
  },
  {
    id: 55,
    user: "rita",
    pass: "1234",
    country: "UK",
    nombre: "Rita Ora",
  },
  {
    id: 56,
    user: "shakira",
    pass: "1234",
    country: "Colombia",
    nombre: "Shakira",
  },
  {
    id: 57,
    user: "lewis",
    pass: "1234",
    country: "UK",
    nombre: "Lewis Hamilton",
  },
  {
    id: 58,
    user: "maria",
    pass: "1234",
    country: "Spain",
    nombre: "María Pedraza",
  },
  {
    id: 59,
    user: "juan",
    pass: "1234",
    country: "Argentina",
    nombre: "Juan Martín del Potro",
  },
  {
    id: 60,
    user: "kylie",
    pass: "1234",
    country: "USA",
    nombre: "Kylie Jenner",
  },
  {
    id: 61,
    user: "david",
    pass: "1234",
    country: "UK",
    nombre: "David Beckham",
  },
  {
    id: 62,
    user: "pablo",
    pass: "1234",
    country: "Argentina",
    nombre: "Pablo Lescano",
  },
  {
    id: 63,
    user: "camila",
    pass: "1234",
    country: "Mexico",
    nombre: "Camila Cabello",
  },
  {
    id: 64,
    user: "alicia",
    pass: "1234",
    country: "Spain",
    nombre: "Alicia Sánchez",
  },
  {
    id: 65,
    user: "drake",
    pass: "1234",
    country: "Canada",
    nombre: "Drake",
  },
  {
    id: 66,
    user: "messi",
    pass: "1234",
    country: "Argentina",
    nombre: "Lionel Andrés Messi",
  },
  {
    id: 67,
    user: "ana",
    pass: "1234",
    country: "Chile",
    nombre: "Ana Tijoux",
  },
  {
    id: 68,
    user: "max",
    pass: "1234",
    country: "Paises Bajos",
    nombre: "Max Verstappen",
  },
  {
    id: 69,
    user: "pepe",
    pass: "1234",
    country: "Argentina",
    nombre: "Guillermo Francella",
  },
];

export default usuarios;
